### ISSUE TITLE
Results bekggeocoder_offline, column "GEM"

### ISSUE THREAD

**Issue by annestroppe** [StefanJuenger/bkggeocoder#2]
It seems like the column GEM contains the identification of a "Verbandsgemeinde" and not of a "Gemeinde". 

See: https://www.destatis.de/DE/Themen/Laender-Regionen/Regionales/Gemeindeverzeichnis/Glossar/regionalschluessel.html 
12-stelliger Schlüssel zur eindeutigen Identifizierung einer Gemeinde mit den Bestandteilen: Bundesland (2 Stellen), Regierungsbezirk (1 Stelle), Kreis (2 Stellen), Gemeindeverband (4 Stellen) und Gemeinde (3 Stellen).

**Comment by JsLth** [comment]
I changed the column names so that they follow the official set of abbreviations of the BKG (see [here, page 9](https://sg.geodatenzentrum.de/web_public/gdz/dokumentation/deu/vg250_01-01.pdf)).

**Comment by annestroppe** [comment]
I would suggest to keep the RS and include the AGS additionally to RS and VWG (same BKG, source, p. 6). The AGS(=GKZ) is usually included in all administrative data and, hence, most usually used to link to other data sources.

   `RS  = messy_data$RS,`
    `AGS = paste0(substr(messy_data$RS, 1, 5),substr(messy_data$RS, 10, 12), sep = ""),`
    `VWG = substr(messy_data$RS, 1, 9),`
